version: '3.1'
volumes:
  postgresql: {}

services:
  db:
    container_name: Postgres
    image: postgres:10
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres