version: '2.1'
volumes: 
  citus_worker: {}
services:
  worker:
    container_name: citus_worker
    image: 'citusdata/citus:7.5.1'
    ports: 
      - 5432:5432
    labels: ['com.citusdata.role=Worker']
    volumes: 
      - citus_worker:/var/lib/postgresql/data
    environments:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=citus
